version: '3'

services:

   grafana:
      image: 'grafana/grafana:8.0.4'
      environment:
         - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
         - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
         - GF_USERS_ALLOW_SIGN_UP=false
      ports:
         - '3000'
      restart: unless-stopped
