version: '3'

services:
   mysql:
      image: 'mariadb:10.6.2'
      ports:
         - 3306
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=peanut
         - MYSQL_USER=peanut
         - MYSQL_PASSWORD=secret
         - MYSQL_ALLOW_EMPTY_PASSWORD=no
      restart: unless-stopped
