version: '3'

services:

   etcd:
      image: 'minio/minio:RELEASE.2021-06-17T00-10-46Z-28-gac7697426'
      command: server /data --console-address ":9001"
      environment:
         - MINIO_ROOT_USER=peanut
         - MINIO_ROOT_PASSWORD=secret
      ports:
         - '9000'
         - '9001'
      restart: unless-stopped
