version: '3'

services:
   postgres:
      image: 'postgres:13.3'
      ports:
         - 5432
      environment:
         - POSTGRES_USER=dbuser
         - POSTGRES_PASSWORD=dbpass
         - POSTGRES_DB=dbname
      restart: unless-stopped
