version: '3'

services:

    # Prometheus Service
    prometheus:
        image: 'prom/prometheus:v2.28.1'
        volumes:
            - '/root/prometheus.yml:/etc/prometheus/prometheus.yml'
        ports:
            - '9090'
        restart: unless-stopped
