version: '3'

services:
  peanut:
    image: 'clivern/peanut:release-v0.1.0'
    ports:
      - "8000:8000"
    command: '/app/peanut api -c /app/configs/config.yml'
    volumes:
      - './configs/:/app/configs'
    restart: unless-stopped

  etcd:
    image: docker.io/bitnami/etcd:3-debian-10
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
    restart: unless-stopped

volumes:
  etcd_data:
    driver: local
