name: API

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18', '1.19', '1.20.4']
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make install_revive

      - name: Install etcd server
        run: |
          bash ./bin/local_etcd_ubuntu.sh

      - name: Run make ci
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make ci
          make integration
          make integration
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify
